In [4]:
import pandas as pd

In [6]:
df_csv = pd.read_csv('data.csv', encoding='shift-jis')

In [8]:
df_csv

     都道府県コード 都道府県名  元号  和暦（年）   西暦（年）   人口（総数）    人口（男）    人口（女）
0          1   北海道  大正    9.0  1920.0  2359183  1244322  1114861
1          2   青森県  大正    9.0  1920.0   756454   381293   375161
2          3   岩手県  大正    9.0  1920.0   845540   421069   424471
3          4   宮城県  大正    9.0  1920.0   961768   485309   476459
4          5   秋田県  大正    9.0  1920.0   898537   453682   444855
..       ...   ...  ..    ...     ...      ...      ...      ...
934       43   熊本県  平成   27.0  2015.0  1786170   841046   945124
935       44   大分県  平成   27.0  2015.0  1166338   551932   614406
936       45   宮崎県  平成   27.0  2015.0  1104069   519242   584827
937       46  鹿児島県  平成   27.0  2015.0  1648177   773061   875116
938       47   沖縄県  平成   27.0  2015.0  1433566   704619   728947

[939 rows x 8 columns]

In [10]:
df_csv = pd.read_csv('data.csv', encoding='shift-jis', index_col = 1)
df_csv

       都道府県コード  元号  和暦（年）   西暦（年）   人口（総数）    人口（男）    人口（女）
都道府県名
北海道          1  大正    9.0  1920.0  2359183  1244322  1114861
青森県          2  大正    9.0  1920.0   756454   381293   375161
岩手県          3  大正    9.0  1920.0   845540   421069   424471
宮城県          4  大正    9.0  1920.0   961768   485309   476459
秋田県          5  大正    9.0  1920.0   898537   453682   444855
...        ...  ..    ...     ...      ...      ...      ...
熊本県         43  平成   27.0  2015.0  1786170   841046   945124
大分県         44  平成   27.0  2015.0  1166338   551932   614406
宮崎県         45  平成   27.0  2015.0  1104069   519242   584827
鹿児島県        46  平成   27.0  2015.0  1648177   773061   875116
沖縄県         47  平成   27.0  2015.0  1433566   704619   728947

[939 rows x 7 columns]

In [18]:
df_csv[(df_csv['都道府県コード']==44) & (df_csv['元号'] == '平成')]

       都道府県コード  元号  和暦（年）   西暦（年）   人口（総数）   人口（男）   人口（女）
都道府県名
大分県         44  平成    2.0  1990.0  1236942  584672  652270
大分県         44  平成    7.0  1995.0  1231306  581909  649397
大分県         44  平成   12.0  2000.0  1221140  575985  645155
大分県         44  平成   17.0  2005.0  1209571  569796  639775
大分県         44  平成   22.0  2010.0  1196529  564890  631639
大分県         44  平成   27.0  2015.0  1166338  551932  614406